name: Deploy app
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest main
        uses: actions/checkout@main

      - name: Generate package to deploy
        run: zip -r deploy.zip * -x "**node_modules**"

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-aws-demo
          environment_name: Dockerawsdemo-env
          version_label: "docker-aws-demo"
          region: eu-west-1
          deployment_package: deploy.zip
